ktor:
    application:
        modules:
            - com.ktservice.ApplicationKt.module
    deployment:
        port: 8080
        connectionGroupSize: 2
        workerGroupSize: 5
        callGroupSize: 10
        shutdownGracePeriod: 2000
        shutdownTimeout: 3000

server:
    location: Europe/Dublin
